apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: foos.example.com  #<plural>.<group>　CRDの識別子
spec:
  group: example.com    #エンドポイントURLの一部
  names:
    kind: Foo     #Goの構造体名に対応する大文字ではじまり単数形。CRオブジェクトのkindフィールド値
    plural: foos   #リソース名の集合形
  scope: Namespaced   #どのようにインスタンスを分けるか(Namespaced or Cluster)
  versions:
    - name: v1alpha1
      served: true    #このバージョンでAPIサービングを有効化するか(true or false)
      storage: true   #このバージョンでetcd上の永続ストレージ形式を有効化するか(true or false)
      additionalPrinterColumns:  #kubectl get foo で表示したい要素を記述
        - name: Test String
          jsonPath: .testString
          type: string
        - name: Test Integer
          jsonPath: .testNum
          type: integer
      schema:
        openAPIV3Schema:
          type: object
          properties:
            testString:
              type: string
            testNum:
              type: integer